apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tkn-helloworld
spec:
  type: git
  params:
    - name: url
      value: https://github.com/arthurk/tekton-example
    - name: revision
      value: master